# Generated by Django 5.1.7 on 2025-03-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_alter_comision_horario_alter_comision_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
