# Generated by Django 5.1.7 on 2025-03-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_comision_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='cupos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
