# Generated by Django 5.1.7 on 2025-03-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0007_remove_materia_comisiones_materiacomision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='materiacomision',
            name='horario',
        ),
        migrations.AddField(
            model_name='horario',
            name='dias',
            field=models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=100),
        ),
        migrations.AddField(
            model_name='materiacomision',
            name='horarios',
            field=models.ManyToManyField(blank=True, to='gestor.horario'),
        ),
    ]
