# Generated by Django 5.1.7 on 2025-03-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0008_remove_horario_dia_remove_horario_materia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora_fin',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.CharField(),
        ),
    ]
