# Generated by Django 5.1.4 on 2025-04-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0009_alter_horario_hora_fin_alter_horario_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
