# Generated by Django 5.1.7 on 2025-04-02 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0010_inscripcion_aprobado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='materia',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='materia_comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor.materiacomision'),
        ),
    ]
