# Generated by Django 5.1.7 on 2025-04-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0012_alter_profesor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
