# Generated by Django 5.1.4 on 2025-04-02 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0014_remove_materia_profesor_rolprofesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolprofesor',
            name='materia',
        ),
        migrations.AddField(
            model_name='rolprofesor',
            name='materia_comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor.materiacomision'),
        ),
    ]
