# Generated by Django 5.1.7 on 2025-05-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0015_remove_rolprofesor_materia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora_fin',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.CharField(max_length=10),
        ),
    ]
