# Generated by Django 5.1.7 on 2025-11-17 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0016_alter_horario_hora_fin_alter_horario_hora_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['dia', 'hora_inicio']},
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dias',
        ),
        migrations.AlterUniqueTogether(
            name='materiacomision',
            unique_together={('materia', 'comision')},
        ),
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='Lunes', max_length=20),
        ),
        migrations.AddField(
            model_name='horario',
            name='materia_comision',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gestor.materiacomision'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='año_cursada',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='profesor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='materia_comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.materiacomision'),
        ),
        migrations.AlterField(
            model_name='rolprofesor',
            name='materia_comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.materiacomision'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('alumno', 'materia_comision', 'año_cursada')},
        ),
        migrations.AlterUniqueTogether(
            name='rolprofesor',
            unique_together={('profesor', 'materia_comision')},
        ),
        migrations.RemoveField(
            model_name='materiacomision',
            name='horarios',
        ),
    ]
